friendzone/urls.py
from django.contrib import admin
from django.urls import path,include
from project import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.frontpage,name='front'),
    path('project/',include('project.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/urls.py
from django.urls import path
from project import views

app_name = 'project'


urlpatterns = [
    path('dashboard/',views.dashboard,name='dash'),
    path('about/',views.about,name='abo'),
    path('album/',views.album,name='alb'),
    path('contact/',views.contactview,name='con'),
    path('s_account/',views.settings_account,name='account'),
    path('s_basicinfo/',views.settings_basicinfo,name='basic'),
    path('s_education/',views.settings_education,name='education'),
    path('s_interest/',views.settings_interests,name='interest'),
    path('s_password/',views.settings_password,name='password'),
    path('timeline/',views.timeline,name='time'),
    path('uslogin/',views.uslogin,name='login'),
    path('uslogout/',views.uslogout,name='logout'),
    path('find_friend/',views.find_friend,name='find_friend'),
    path('friends/',views.friends,name='friends'),
    path('friend/',views.friend,name='friend'),
    path('follow/',views.follow,name='follow'),
    path('friendRequest/',views.friendRequest,name='friendRequest'),
    path('ConfDel/',views.ConfDel,name='ConfDel'),
    path('messages/',views.messages,name='messages'),
    path('notification/',views.notification,name='notification'),
    path('forgot_password/',views.forgot_password,name='forgot_password'),
    path('hide_notification',views.hide_notification,name="hide_notification"),

    path('user_inbox',views.user_inbox,name="user_inbox"),
    path('user/ajax/message/',views.save_message_ajax,name='ajax_message'),
    path('user/inbox/all/',views.show_message_all,name='show_message'),
    path('user/name/ajax',views.ajax_fun,name='ajax_fun'),
    path('mark_as_read',views.mark_as_read,name='mark_as_read'),
    path('like_unlike',views.like_unlike,name='like_unlike'),
    path('view_likes',views.view_likes,name='view_likes'),
    path('comments',views.comments,name='comments'),

    path('checkn',views.checkn,name="checkn"),
    path('check_user',views.check_user,name="check_user"),
    path('check_request',views.check_request,name="check_request"),

]
    

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="shortcut icon" href="{% static 'images/friendzone2.png' %}">
    <script src="{% static 'jquery.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" >    
    <link href="https://fonts.googleapis.com/css?family=Acme|Satisfy" rel="stylesheet">
    {% block mystyle %}
        
    {% endblock %}
    <style>
        .logo{
            border-radius:50%; 
            height:30px; 
            font-size: 25px;
        } 
    </style>
</head>
<body>
    <div class="container-fluid" style="overflow:hidden;">
        <div class="row">
            <div class="col-md-12">
                <nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top">
                        <a href="{%url 'project:dash'%}" class="navbar-brand">
                    <img src="{% static 'images/friendzone2.png' %}" alt="" class="logo">
                    FriendZone</a>
                    <button class="navbar-toggler" data-toggle="collapse" data-target="#mynav">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div id="mynav" class="collapse navbar-collapse">
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item"><a href="{% url 'project:dash' %}" class="nav-link">Home</a></li>
                            <li class="nav-item"><a href="{% url 'project:find_friend' %}" class="nav-link">FindFriends</a></li>
                            <li class="nav-item"><a href="{% url 'project:friendRequest' %}" class="nav-link"><i class="fas fa-user-friends"></i></a></li>
                            <li class="nav-item"><a href="{% url 'project:messages' %}" class="nav-link"><i class="far fa-comments"></i></a></li>                            
                            <li class="nav-item"><a href="{% url 'project:notification'%}" class="nav-link" ><i class="fas fa-bell" onclick="hidenot('{{request.user.id}}')"></i> <sup class="badge badge-pill badge-danger m-0 unreads" id="" style="position:relative;top:-12px; left:-15px;">{{total}}</sup> </a> </li>
                            <li class="nav-item"><a href="{% url 'project:basic' %}" class="nav-link"><i class="fas fa-user-cog"></i></a></li>
                            <li class="nav-item"><a href="{% url 'project:logout' %}" class="nav-link"><i class="fas fa-sign-out-alt"></i></a></li>
                        </ul>
                    </div>
                </nav>
            </div>
        </div>
        <script>
        $(function(){
            $.ajax({
                url:"{% url 'project:checkn'%}",
                type:'get',
                data:{id:'{{user.id}}'},
                success:function(data){
                    
                    $('.unreads').html(data);
                    if(data==0){
                        $('.unreads').removeClass('badge badge-danger badge-pill').html(' ');
                    }
                }
            })
        })
        
        </script>
        <script>
        function hidenot(id){
            // alert(id);
            $.ajax({
                url:'{% url "project:hide_notification"%}',
                type:'get',
                data:{id:id},
                success:function(data){
                   
                    $('.unreads').removeClass('badge badge-pill badge-danger').html(' ');
                }
            })
        }
        </script>
        {% block mycode %}

        {% endblock %}
    </div>
    {% block timeline %}
    {% endblock %}
    <hr style="background:linear-gradient(lightblue,skyblue); height:10px; border-radius: 50%;"/>
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-md-3 col-sm-3">
                    <img src="{% static 'images/friendzone2.png' %}" class="logo" />
                        <span class="text-muted" style="font-weight:bold; font-size:30px;">FriendZone</span>
                    <em>Connect with friends and the world around you on friendZone!!!
                        </em>
                    
                </div>
                <div class="col-md-2 col-sm-2 mt-3">
                  
                </div>
                <div class="col-md-2 col-sm-2 mt-3">
                  
                </div>
                <div class="col-md-2 col-sm-2 mt-3">
                  
                </div>
                <div class="col-md-3 col-sm-3 mt-3">
                    <p class="text-primary">Contact Us</p>
                    <p>#C-86, Industrial Area, phase-7 Mohali, India</p>
                </div>
            </div>
        </div>
    </footer>
    {% block myscript %}
    {% endblock%}
</body>
</html>

templates/dashboard.html
{% extends 'base.html' %}
{% block mystyle %}
<style>
    .box{
        width: 100%;
        height:100px;
        background: rgba(0, 0, 255,0.5);
        border-radius: 2%;
    }
    .pill{
        background: green;
        width:100%;
        height: 40px;
        line-height: 40px;
        border-radius: 25px;
        color:white;
        padding-left: 30%;
    }
    .photo{
        border-radius: 50%;
        height:90px;
        width:90px;
        border: 7px solid white; 
        position: relative; 
        top:-20px
    }
    .online{
        border-radius: 50%;
        height:70px;
        width: 70px;
        margin-right: 10px;
        margin-bottom: 10px;
        margin-top: 10px;
        margin-left: 0 auto;
    }
    .dot{
        background: rgb(11, 247, 11);
        height: 10px;
        width: 10px;
        border-radius: 50%;
        position: relative;
        top: -17px;
        left: 30px;
    }
</style>
{% endblock %}
{% block mycode %}
{% load staticfiles %}

        <div class="row">
            <div class="col-md-12">
                <br/><br/><br/><br/>
            </div>
        </div>
        <div class="row ml-5">
            <div class="col-md-3" style="position: sticky;">
                <div class="row box">
                    <div class="col-md-5">
                            {% if profile.profile_pic %}
                            <img src="/media/{{profile.profile_pic}}" class="photo">
                            
                            {% else %}
                            <img src="/media/no_image.png" alt="" class="photo">
                            {% endif %}
                    </div>
                    <div class="col-md-7">
                            <h5><a href="" class="text-white" >{{user.first_name}} {{user.last_name}}</a></h5>
                        <a href="" class="text-white" ><i class="ion ion-android-person-add"></i> {{fff}} followers</a>
                    </div>
                </div>
                <div><br/> <br/> <br/></div>
                <div class="row">
                    <div class="col-md-12 sticky-top" >
                        <img src="{% static 'images/newsfeed.png' %}" alt="" style="height:20px;">&nbsp;&nbsp;&nbsp;
                        <a href="{% url 'project:time' %}" style="color:grey">Timeline</a> <hr/>
                        <img src="{% static 'images/nearby.png' %}" alt="" style="height:16px;">&nbsp;&nbsp;
                        <a href="{% url 'project:friends' %}" style="color:grey">Friends</a> <hr/>
                        <img src="{% static 'images/messages.jpg' %}" alt="" style="height:18px;">
                        <a href="{% url 'project:messages' %}" style="color:grey">Messages</a> <hr/>
                        <img src="{% static 'images/settings.png' %}" alt="" style="height:18px;">
                        <a href="{% url 'project:basic' %}" style="color:grey">Settings</a> <hr/>
                        <img src="{% static 'images/Signout.png' %}" alt="" style="height:18px;">
                        <a href="{% url 'project:logout' %}" style="color:grey">Logout</a> <hr/>
                    </div>
                </div>
            </div>
            <div class="col-md-7">
                <form action="" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-1">
                            {% if profile.profile_pic %}
                            <img src="/media/{{profile.profile_pic}}" style="border-radius:50%; height:60px; width:60px;">
                            
                            {% else %}
                            <img src="/media/no_image.png" alt="" style="border-radius:50%; height:60px; width:60px;">
                            {% endif %}
                            <!-- <img src="/media/{{profile.profile_pic}}" style="border-radius:50%; height:60px; width:60px;"> -->
                        </div>
                        <div class="col-md-5">
                            <textarea cols="40" rows="2" class="form-control ml-2" name="content"></textarea>
                        </div>
                        <div class="col-md-3">
                            <ul class="list-inline" type = none>
                                <li>
                                    <i class="far fa-images text-dark ml-2 mt-4" style="float:left;position:relative;">
                                        <input type="file" name="media" class="form-control" style="height:10px;width:40px;position:absolute;top:0px;opacity:0.1;" >                                        
                                    </i>
                                </li>
                                <li><a href=""><i class="fas fa-video text-dark ml-2 mt-4" style="float:left;"></i></a></li>
                            </ul>
                        </div>
                        <div class="col-md-3">
                            <button class="btn btn-primary text-white mt-2" type="submit" name="postupload" style="border-radius:25px;width:100%;"><h6>Publish</h6></button>
                        </div>
                    </div>
            </form>
                <hr class="mb-4 mt-3"/>
                {% for i in all %}
                <div class="row mb-3" style="background:whitesmoke">
                    <div class="col-md-12 mb-3 mt-3">
                        
                        <img src="/media/{{i.media}}" alt="" style="height:400px; width:100%; background-size: cover">
                        <div class="row mt-4" >
                            <div class="col-md-2 ">
                                {% if i.user.profile_pic %}
                                <img src="/media/{{i.user.profile_pic}}" style="border-radius:50%; height:60px; width:60px;">
                                
                                {% else %}
                                <img src="/media/no_image.png" alt="" style="border-radius:50%; height:60px; width:60px;">
                                {% endif %}
                            </div>
                            <div class="col-md-10">
                                <div class="row">
                                    <div class="col-md-9">
                                        <p><a href=""><span class="m-0" style="font-size:20px; font-weight: bold;">{{i.user.user.first_name}} {{i.user.user.last_name}}</span></a>
                                        &nbsp;&nbsp;<span style="color:chartreuse;">following</span></p>
                                        <p class="text-muted">{{i.upload_on}}</p>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="row">
                                            <div class="col-md-6">
                                                <a onclick="like('{{i.id}}')"><i class="fas fa-thumbs-up p-{{i.id}}"  style="font-size:25px;"></i></a>
                                            </div>
                                            <div class="col-md-6">
                                                    <script>
                                                        $(function(){  
                                                            
                                                            $.ajax({
                                                                url:'{% url "project:view_likes" %}',
                                                                data:{pid:'{{i.id}}'},
                                                                type:'get',
                                                                success:function(data){  
                                                                       
                                                                    $('.t-{{i.id}}').html(data.comm+' likes');
                                                                    $('.p-{{i.id}}').addClass(data.color);
                                                                    }
                                                            })
                                                        });
                                                    </script>
                                                <span class="t-{{i.id}}"></span>

                                            </div>
                                            
                                        </div>
                                    </div>
                                </div>
                                
                                <p class="text-muted">{{i.content}}</p>
                                <hr/>
                                {% for j in comm %}
                                    {% if j.postid.id == i.id%}
                                    <div class="row">
                                        <div class="col-md-2">
                                            <img src="/media/{{j.commenterid.profile_pic}}" alt="" style="border-radius:50%; height:60px; width:60px;">
                                        </div>
                                        <div class="col-md-10">
                                            <p class="text-muted mt-2">{{j.comment}}</p>
                                            <small class="float-right">{{j.create_date}}</small>
                                            
                                        </div>
                                    </div>
                                    <hr>
                                    {% endif %}
                                {% endfor %}
                                
                                <form action="{% url 'project:comments'%}" method="post">
                                    {% csrf_token %}
                                    <div class="row">
                                        <div class="col-md-9">
                                            <input type="hidden" name = "postid" value="{{i.id}}">
                                            <input type="hidden" name = "userid" value="{{request.user.id}}">
                                            <input type="text" name="comment" id="" class="form-control">
                                        </div>
                                        <div class="col-md-3">
                                            <input type="submit" name="" id="" class="btn btn-primary form-control">
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
            <div class="col-md-2">
                <h6 class="pill mt-2">Chat Online</h6>
                <hr class="mt-4" />
                <div class="row">
                    <div class="col-md-6 mx-auto">
                        {% for i in onlines %}
                        <a href="{% url 'project:user_inbox'%}?id={{i.user.id}}">
                            {% if i.profile_pic %}
                            <img src="/media/{{i.profile_pic}}" alt="" class="online">
                            {% else %}
                            <img src="/media/no_image.png" alt="" class="online">
                            {% endif %}
                            <div class="dot m-0"></div>
                        </a>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
        <script>
        function like(pid){  
            $.ajax({
                url:'{% url "project:like_unlike" %}',
                data:{pid:pid,uid:'{{request.user.id}}'},
                type:'get',
                success:function(data){      
                    if(data.action=="Liked"){
                        $('.p-'+pid).addClass('text-primary').removeClass('text-secondary');
                        $('.t-'+pid).html(data.all+' likes');
                        
                    }else{
                        $('.p-'+pid).addClass('text-secondary').removeClass('text-primary');
                        $('.t-'+pid).html(data.all+' likes');
                    }
                  }
            })
        }


        function comment(cid){
            $.ajax({
                url:'{% url "project:comments" %}',
                data:{cid:cid,uid:'{{request.user.id}}'},
                type:'get',
                success:function(data){
                    
                }
            })
        }
        </script>


        {% endblock %}

templates/settings_interests.html
{% extends 'base.html' %}
{% block mystyle %}
<style>
        .logo{
            border-radius:50%; 
            height:30px; 
            font-size: 25px;
        }
        .back{
            background: url("{% if profile.cover_pic %}/media/{{profile.cover_pic}}{% else%}/media/cover.jpg{% endif %}");
            height:400px; 
            padding-top: 300px; 
            background-size:cover; 
            width:100%
        }
        .photo{
            height:200px; 
            width:200px; 
            border-radius:50%; 
            border: 10px solid white;
            position: relative;
            top: -90px;
        }
        .line{
            word-spacing:10px;
            line-height:70px;
        }
        .sidebar-circle{
            height:20px;
            width:20px;
            background:lightgreen;
            border-radius:50%; 
            margin:0 auto; 
            margin-top: 50px;
        }
        .sidebar-line{
            height:930px;
            width:2px;
            background:lightgreen;margin:0 auto
        }
        .a{
            display: inline;
        }
        .rg{
            background:rgba(0, 0, 0, 0.8);  
            height:70px; 
            text-align:center;
        }
        .buton{
            background: blue;
            border-radius:25px; 
            width:100%;
        }
        .smal{
            text-align: left;
            margin-left: 50px;
        }
        .publish{
            border-radius:25px;
            width:100%;
            position: relative;            
        }
        .len{
            width:100%;
            position: relative;
            top:0px;
        }
        .play{
            display: none !important;
        }
        .playbt{
            display: none !important;
        }
        @media screen and (max-width:700px){
            .sidebar-circle{
                background:red;
                display:none !important;
            }
            .a{
                display: none !important;
            }
            .sidebar-line{
            display:none !important;
            }
            .rg{
                background:transparent;
            }
            .buton{
                background:transparent;
            } 
            .smal{
                text-align: center;
                margin-left: 0px;
            }
            .publish{
                width:50%;
                top:-40px;
                float: right;
            }
            .len{
                width:70%;
                top:-60px;
                float: right;
                margin-right:10px;
            }
            .play{
                display: inline !important;
                margin-left: 100px;
                word-spacing: 15px;
            }
            .playbt{
                display: inline !important;
                margin-left: 20%;
                border-radius: 25px;
            }
        }
        
    </style>
{% endblock %}
{% block timeline %}
{% load staticfiles %}
    <div class="container">
        <div class="row back">
            <div class="col-md-12 rg" >
                <div class="row">
                    <div class="col-md-3">
                        {% if profile.profile_pic %}
                        <img src="/media/{{profile.profile_pic}}" class="photo">
                        
                        {% else %}
                        <img src="/media/no_image.png" alt="" class="photo">
                        {% endif %}
                    </div>
                    <div class="col-md-4 line">
                        <a href="{% url 'project:time' %}" style="color:white;" class="a">Timeline</a>
                        <a href="{% url 'project:abo' %}" style="color:white;" class="a">About</a>
                        <a href="{% url 'project:alb' %}" style="color:white;" class="a">Album</a>
                        <a href="{% url 'project:friend' %}" style="color:white;" class="a">Friends</a>
                    </div>
                    <div class="col-md-3">
                        <!-- <p style="color:white;line-height: 70px; margin-left: 50px;" class="a">{{fff}} followers</p> -->
                    </div>
                    <!-- <div class="col-md-2" style="line-height: 70px;">
                        <button class="btn btn-primary text-white m-0 a"><h6>Add Friend</h6></button>                        
                    </div>                   -->
                </div>
            </div>

            <!-- copied -->

            <div class="col-sm-12 col-12 small" style="display:none">
                <img src="/media/{{profile.profile_pic}}" class="photo">                
            </div>

            <!-- end -->

        </div>
        <div class="row">
            <div class="col-md-12">
                &nbsp;
            </div>
        </div>
        <div class="row">
            <div class="col-md-3">
                <h4 class="text-primary smal">{{user.first_name}} {{user.last_name}}</h4>
                <p class="text-muted smal">{{profile.profession}}</p>
                <div class="play">
                    <a href="{% url 'project:time' %}" style="color:blue;" >Timeline</a>
                    <a href="{% url 'project:abo' %}" style="color:black;" >About</a>
                    <a href="{% url 'project:alb' %}" style="color:black;" ">Album</a>
                    <a href="{% url 'project:friend' %}" style="color:black;" >Friends</a>
                </div>
                <!-- <div style="line-height: 70px;" class="playbt">
                    <button class="btn btn-primary text-white mb-5 mt-3 playbt"><h6>Add Friend</h6></button>                        
                </div> -->
                <ul type="none" class="mt-5">
                    <li class="my-2"> <a href="{% url 'project:basic' %}" style="color:black"><i class="fas fa-info-circle m-2"></i><span>Basic Infomation</span></a></li><hr>
                    <li class="my-2"> <a href="{% url 'project:education' %}" style="color:black"><i class="fas fa-briefcase m-2"></i><span>Education and Work</span> </a></li><hr>
                    <li class="my-2" style="border-left:2px solid lightgreen;"> <a href="{% url 'project:interest' %}" style="color:black"><i class="fas fa-heart m-2"></i><span>My Interests</span></a></li><hr>
                    <!-- <li class="my-2"> <a href="{% url 'project:account' %}" style="color:black"><i class="fas fa-sliders-h m-2"></i><span>Account Settings</span></a></li><hr> -->
                    <li class="my-2"> <a href="{% url 'project:password' %}" style="color:black"><i class="fas fa-lock m-2"></i><span>Change Password</span> </a></li><hr>
                </ul>
            </div>
            <div class="col-md-7">
                <i class="fas fa-heart m-2 text-info" style="font-size:20px;"></i><span class="m-2" style="font-size:20px;">My Interests</span> <hr>
                <p class="text-muted">“The beauty and mystery of this world only emerges through affection, attention, interest and compassion . . . open your eyes wide and actually see this world by attending to its colors, details and irony.” </p> <hr>
                <div class="row">
                    <div class="col-md-12">
                        {% for i in interest %}
                        <div class="bg-success p-2 d-inline text-white"style="border-radius:20px;text-decoration:none;margin:10px;">&nbsp {{i.add_interest}}
                        <a href="{% url 'project:interest' %}?id={{i.id}}">
                        <span class="badge badge-danger badge-pill">&times;</span>

                        </a>
                    </div>
                       {% endfor %}
                        <hr>
                    </div>
                </div>
                <form action="" method="POST">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-12">
                            <p class="text-muted">Add Interests</p>
                        </div>
                        
                        <div class="col-md-8">
                            <div class="form-group">
                                <input type="text" name="interest" pattern="[A-Za-zs\]" id="" class="text-muted form-control" placeholder="Interests e.g. Photography,Singing" title="It should contain Alphabets and white spaces only">
                            </div>
                        </div>
                        <div class="col-md-4">
                            <button class="btn btn-primary btn-block" type="submit" value="Save Changes" >Add</button>
                        </div>
                </div>
            </form>
            </div>
            <div class="col-md-2" >
                <p class="text-muted" >{{user.first_name}} {{user.last_name}} Activity</p>
                {% for i in act %}
                <!-- <p class="text-muted mb-1" style="border-left:2px solid green;"><a href="" class="text-primary" >{{i.user.user.first_name}}</a></p> -->
                <p class="text-muted" style="border-left:2px solid green;">{{i.content}}</p>
                <p class="text-muted">{{i.time}}</p>
                <hr/>
                {% endfor %}
            </div> 
        </div>
    </div>
    {% endblock %}
    